#!/usr/bin/env bash
# Pings five times an IP address

if [ "$1" ]; then
    ping -c 5 "$1"
elif [ "$#" -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
